############################################################
# MULTI-DATASET RNA-SEQ DESEQ2 DIFFERENTIAL EXPRESSION
# Script: script/05_rnaseq_differential_expression.R
############################################################

############################################################
# SETTINGS & CONFIGURATIONS
############################################################
options(stringsAsFactors = FALSE)
set.seed(123)

############################################################
# LIBRARIES
############################################################
library(DESeq2)
library(dplyr)
library(tibble)

############################################################
# DIRECTORY INFRASTRUCTURE
############################################################
dir.create("results/rna_individual", showWarnings = FALSE, recursive = TRUE)

############################################################
# TARGET COHORT CONFIGURATIONS
# Explicitly references the 8 sequencing cohorts from Table 3
############################################################
rna_datasets <- c(
  "GSE132074", "GSE144957", "GSE222410", "GSE113754", 
  "GSE211088", "GSE211301", "GSE156925", "GSE166831"
)

############################################################
# CORE DESEQ2 GENERALIZED LINEAR MODEL LOOP
############################################################
for(ds in rna_datasets) {
  
  cat("====================================================\n")
  cat("Processing RNA-seq Cohort via DESeq2 Framework:", ds, "\n")
  cat("====================================================\n")
  
  # Map paths to count matrices generated by your upstream featureCounts shell script
  counts_path   <- paste0("data/RNAseq_counts/", ds, "_raw_counts.txt")
  metadata_path <- paste0("data/metadata/", ds, "_metadata.csv")
  
  # Safe checkpoint validation for missing data assets
  if(!file.exists(counts_path)) {
    cat("Warning: Count matrix missing for", ds, "- Skipping cohort.\n")
    next
  }
  if(!file.exists(metadata_path)) {
    cat("Warning: Metadata reference missing for", ds, "- Skipping cohort.\n")
    next
  }
  
  # 1. Import Count Matrices (skipping the featureCounts informational header rows)
  counts_raw <- read.table(counts_path, header = TRUE, row.names = 1, sep = "\t", skip = 1)
  
  # Subselect only the numeric sample count columns (columns 6 onwards from featureCounts output)
  # mapping to your individual aligned BAM alignments
  counts <- counts_raw[, 6:ncol(counts_raw), drop = FALSE]
  
  # 2. Import Sample Annotations
  coldata <- read.csv(metadata_path, row.names = 1)
  
  # Clean up column names to ensure exact matches between count columns and metadata row keys
  colnames(counts) <- gsub("\\.", "-", colnames(counts))
  
  # 3. Establish Explicit Biological Factor Baselines
  coldata$condition <- factor(coldata$condition, levels = c("Control", "SD"))
  
  # 4. Initialize the DESeqDataSet Object
  dds <- DESeqDataSetFromMatrix(
    countData = counts,
    colData = coldata,
    design = ~ condition
  )
  
  # 5. Independent Filtering: Purge low-count background noise
  # Retain transcripts with a minimum row sum of 10 reads across samples
  keep <- rowSums(counts(dds)) >= 10
  dds <- dds[keep, ]
  
  # 6. Execute Fitted Negative Binomial Model Estimates
  cat("Estimating size factors, dispersions, and fitting GLM walls...\n")
  dds <- DESeq(dds)
  
  # 7. Extract Contrast Statistics (Explicit Direction: Sleep Deprived vs. Control)
  res <- results(dds, contrast = c("condition", "SD", "Control"))
  
  # 8. Extract Native standard errors and LogFC elements
  res_df <- as.data.frame(res) %>%
    rownames_to_column(var = "Gene") %>%
    mutate(
      Gene = toupper(trimws(Gene)), # Normalize gene nomenclatures for seamless cross-platform matching
      dataset = ds
    ) %>%
    # Filter out empty or unmapped gene designations
    filter(!is.na(Gene) & Gene != "") %>%
    # Select critical parameters including the true, native lfcSE standard error
    select(Gene, log2FoldChange, lfcSE, pvalue, padj, dataset)
  
  # 9. Save Standalone Individual Cohort Outputs
  write.csv(
    res_df,
    paste0("results/rna_individual/", ds, "_DESeq2_DEG.csv"),
    row.names = FALSE
  )
  
  cat("Dataset completed successfully. Profile saved to: results/rna_individual/", ds, "_DESeq2_DEG.csv\n")
}

cat("====================================================\n")
echo "All individual RNA-seq DESeq2 differential expression models generated successfully.\n"
